stock_control/compra/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'compra'  

#urls del entorno de compra
urlpatterns = [
    path('', TemplateView.as_view(template_name='base/compra.html'), name='compra'),
    path('lista_productos/', views.lista_productos, name='lista_productos'),
    path('detalle_producto/<int:pk>/', views.detalle_producto, name='detalle_producto'),
    path('crear_producto/', views.crear_producto, name='crear_producto'),
    path('modificar_producto/<int:pk>/', views.modificar_producto, name='modificar_producto'),
    path('eliminar_producto/<int:pk>/', views.eliminar_producto, name='eliminar_producto'),
    path('lista_proveedores/', views.lista_proveedores, name='lista_proveedores'),
    path('detalle_proveedor/<int:pk>/', views.detalle_proveedor, name='detalle_proveedor'),
    path('crear_proveedor/', views.crear_proveedor, name='crear_proveedor'),
    path('modificar_proveedor/<int:pk>/', views.modificar_proveedor, name='modificar_proveedor'),
    path('eliminar_proveedor/<int:pk>/', views.eliminar_proveedor, name='eliminar_proveedor'),
]

stock_control/stock_control/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('compra/', include('compra.urls', namespace='compra')),
    path('', TemplateView.as_view(template_name='base/home.html'), name='home')
]

stock_control/compra/models.py
from django.db import models

# Modelos
# Modelo Proveedor.

class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    dni = models.CharField(max_length=8, unique=True)
    pass
    
    class Meta:
        ordering = ('nombre', 'apellido',)

    def __str__(self):
        return f'{self.nombre} {self.apellido}'


# Modelo Producto.   

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.FloatField()
    stock_actual = models.IntegerField()
    proveedor = models.ForeignKey(Proveedor, on_delete=models.PROTECT,null=True)
    
    class Meta:
        ordering = ('nombre',)

    def __str__(self):
        return f'Producto: {self.nombre}, precio: {self.precio}, stock actual: {self.stock_actual}, proveedor: {self.proveedor}'

stock_control/compra/forms.py
from django import forms
from django.forms import ValidationError
from compra.models import Proveedor,Producto

# Form de Proveedor
class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields= [
            'nombre','apellido','dni'
        ]

    def clean_nombre(self):
       nombre = self.cleaned_data.get('nombre')
       if len(nombre) < 4 :
          raise ValidationError(f'La propiedad nombre debe tener al menos 4 letras.')
       if isinstance(nombre,int):
           raise ValidationError(f'La propiedad nombre debe ser un string.')
       return nombre
    
    def clean_apellido(self):
       apellido = self.cleaned_data.get('apellido')
       if len(apellido) < 4 :
          raise ValidationError(f'La propiedad apellido debe tener al menos 4 letras.')
       if isinstance(apellido,int) :
           raise ValidationError(f'La propiedad apellido debe ser un string.')
       return apellido
    
    def clean_dni(self):
       dni = self.cleaned_data.get('dni')
       if len(dni) < 8 :
          raise ValidationError(f'La propiedad dni debe tener al menos 8 dígitos.')
       if isinstance(dni,float):
           raise ValidationError(f'La propiedad dni debe ser un número.')
       return dni
    

# Form de Producto 
class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields= [
            'nombre','precio','stock_actual','proveedor'
        ]

    def clean_nombre(self):
       nombre = self.cleaned_data.get('nombre')
       if len(nombre) < 4 :
          raise ValidationError(f'La propiedad nombre debe tener al menos 4 letras.')
       if isinstance(nombre,int):
           raise ValidationError(f'La propiedad nombre debe ser un string.')
       return nombre
    
    def clean_precio(self):
       precio = self.cleaned_data.get('precio')
       if isinstance(precio,int):
           raise ValidationError(f'La propiedad precio debe ser un string.')
       return precio
    
    def clean_stock_actual(self):
       stock_actual = self.cleaned_data.get('stock_actual')
       if isinstance(stock_actual,str):
           raise ValidationError(f'La propiedad stock_actual debe ser un número.')
       return stock_actual

stock_control/compra/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import permission_required
from django.urls import reverse

from compra.models import Producto
from compra.models import Proveedor
from compra.forms import ProductoForm
from compra.forms import ProveedorForm

# Vistas de productos

def lista_productos(request):
    productos = Producto.objects.all()
    #renderiza la vista de todos los productos
    return render(request, 'productos/lista_productos.html', {'productos': productos})

def detalle_producto(request, pk):
    producto_detalle = get_object_or_404(Producto, pk=pk)
    # renderiza detalle de producto
    return render(request, 'productos/detalle_producto.html',{'producto_detalle':producto_detalle})

@permission_required('compra.crear_producto', raise_exception=True)
def crear_producto(request):
    if (request.method == 'POST'):
        producto_form = ProductoForm(request.POST) 
        if(producto_form.is_valid()):
            nuevo_producto = producto_form.save(commit=True)
            messages.success(request, 'Se ha agregado el nuevo producto')
            return redirect(reverse('compra:detalle_producto', args={nuevo_producto.id}))
    else:
        producto_form = ProductoForm()

    return render(request, 'productos/producto_form.html', {'form': producto_form})

def modificar_producto(request,pk):
    producto = get_object_or_404(Producto,pk=pk)
    proveedores = Proveedor.objects.all()
    if (request.method == 'POST'):
        nombre = request.POST.get('nombre')
        precio = request.POST.get('precio')
        stock_actual = request.POST.get('stock_actual')
        id_proveedor = request.POST.get('id_proveedor')
        proveedor = get_object_or_404(Proveedor, id= id_proveedor) 

        producto.nombre = nombre
        producto.precio = precio
        producto.stock_actual = stock_actual
        proveedor.proveedor = proveedor
        producto.save()

        return redirect(reverse('compra:lista_productos'))
    
    return render(request, 'productos/producto_modificado.html', {'producto': producto ,'proveedores': proveedores})

def eliminar_producto(request, pk):
    producto = get_object_or_404(Producto,pk=pk)
    if request.method == 'POST':
        producto.delete()
        return redirect(reverse('compra:lista_productos'))
    
    return render (request,'productos/producto_confirm_delete.html', {'producto': producto})


# Vistas de proveedores

def lista_proveedores(request):
    proveedores = Proveedor.objects.all()
    return render(request, 'proveedores/lista_proveedores.html', {'proveedores': proveedores})

def detalle_proveedor(request,pk):
    proveedor_detalle = get_object_or_404(Proveedor, pk= pk)
    return render(request, 'proveedores/detalle_proveedor.html',{'proveedor_detalle': proveedor_detalle} )

@permission_required('compra.crear_proveedor', raise_exception=True)
def crear_proveedor(request):
    if (request.method == 'POST'):
        proveedor_form = ProveedorForm(request.POST)
        if(proveedor_form.is_valid()):
            nuevo_proveedor = proveedor_form.save(commit=True)
            messages.success(request, 'Se ha agregado un nuevo proveedor')
            return redirect(reverse('compra:detalle_proveedor', args={nuevo_proveedor.id}))
    else:
        proveedor_form = ProveedorForm()

    return render(request, 'proveedores/proveedor_form.html', {'forms': proveedor_form})

def modificar_proveedor(request,pk):
    proveedor = get_object_or_404(Proveedor,pk=pk)
    if(request.method == 'POST'):
        nombre = request.POST.get('nombre')
        apellido = request.POST.get('apellido')
        dni = request.POST.get('dni')
        proveedor.nombre = nombre
        proveedor.apellido = apellido
        proveedor.dni = dni
        proveedor.save()

        return redirect(reverse('compra:lista_proveedores'))
    
    return render(request, 'proveedores/proveedor_modificado.html', {'proveedor': proveedor})

def eliminar_proveedor(request,pk):
    proveedor = get_object_or_404(Proveedor,pk=pk)
    if request.method == 'POST':
        proveedor.delete()
        return redirect(reverse('compra:lista_proveedores'))
    
    return render (request,'proveedores/proveedor_confirm_delete.html', {'proveedor': proveedor})

stock_control/compra/templates/base/compra.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Control</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-success border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          <span class="navbar-brand">Stock Control</span>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="http://127.0.0.1:8000/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="http://127.0.0.1:8000/admin/">Admin</a>
              </li>
          </div>
        </div>
    </nav>
    <main class="margin 50px container mt-5">
        <h1>Compra</h1>
        <br>
        <br>
        <h3>Ir a: </h3>
         <br>
         <a class="btn btn-success" href="{% url 'compra:lista_proveedores' %}" role="button">Proveedores</a>
         <a class="btn btn-success" href="{% url 'compra:lista_productos' %}" role="button">Productos</a>
    </main>
    <footer class="mt-5 p-4 bg-success bg-gradient text-white text-center">
        <br>
        <p>Alkemy - Programa: POO en Python</p>
        <br>
    </footer>
</body>
</html>

stock_control/compra/templates/productos/detalle_producto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Control</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-success border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          <span class="navbar-brand">Stock Control</span>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'compra:lista_proveedores' %}">Proveedores</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="http://127.0.0.1:8000/admin/">Admin</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    <main class="container mt-5"> 
        <div class="container mb-3">
        <h1>Detalle del Producto</h1>
        <br>
        <p><strong>Nombre: </strong> {{producto_detalle.nombre}}</p>
        <p><strong>Precio: </strong> {{producto_detalle.precio}}</p>
        <p><strong>Stock Actual: </strong> {{producto_detalle.stock_actual}}</p>
        <p><strong>Proveedor: </strong> {{producto_detalle.proveedor}}</p>
        <hr>
        <a class="text-muted text-decoration-none" href="{% url 'compra:modificar_producto' producto_detalle.id %}">Modificar</a> 
      
        <a class="text-muted text-decoration-none" href="{% url 'compra:eliminar_producto' producto_detalle.id %}">Eliminar</a> 
      
        <a class="text-muted text-decoration-none" href="{% url 'compra:lista_productos' %}">Volver a la lista de Producto</a>
        
        </div>
    </main>
    <footer class="mt-5 p-4 bg-success bg-gradient text-white text-center">
        <br>
        <p>Alkemy - Programa: POO en Python</p>
        <br>
    </footer>
</body>
</html>

stock_control/compra/templates/productos/lista_productos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Control</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-success border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          <span class="navbar-brand">Stock Control</span>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'compra:lista_proveedores' %}">Proveedores</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="http://127.0.0.1:8000/admin/">Admin</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    <main class="container mt-5"> 
      <h2>Lista de Productos</h2>
      <div class="mb-3 ">
          <ol class="list-group">
            {% for producto in productos %}
                <li class="list-group-item">
                  <a class="list-group-item list-group-item-action" href="{% url 'compra:detalle_producto' producto.id %}">
                    {{producto.id}}  -  {{producto.nombre}}  -  {{producto.precio}}  -  {{producto.stock_actual}}  -  {{producto.proveedor}}
                  </a>
                </li>
            {% empty %}
                <li class="list-group-item">No existen productos</li>
            {% endfor %}
        </ol>
        <hr>
        <br>
        <a class="text-muted text-decoration-none" href="{% url 'compra:crear_producto' %}">Crear Producto</a>

      </div>
    </main>
    <footer class="mt-5 p-4 bg-success bg-gradient text-white text-center">
        <br>
        <p>Alkemy - Programa: POO en Python</p>
        <br>
    </footer>
</body>
</html>

stock_control/compra/templates/productos/listas_productos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Control</title>
</head>
<body>
    <header>

    </header>
    <nav>

    </nav>
    <main> 

    </main>
    <footer>
        
    </footer>
</body>
</html>

stock_control/compra/templates/productos/producto_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Control</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-success border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          <span class="navbar-brand">Stock Control</span>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'compra:lista_proveedores' %}">Proveedores</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="http://127.0.0.1:8000/admin/">Admin</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    <main class="container mt-5"> 
        <h2>Eliminación de producto</h2>
        <p>¿Está seguro que desea eliminar este producto: {{producto.nombre}} ?</p>
        <form action="" method="post" class="mb-3 ">
            {% csrf_token %}
            <input type="submit" value="Si, Eliminar" class="form-control btn btn-outline-success">
        </form>
        <br>
        <a class="text-muted text-decoration-none" href="{% url 'compra:detalle_producto' producto.id %}">Cancelar</a>
    </main>
    <footer class="mt-5 p-4 bg-success bg-gradient text-white text-center">
        <br>
        <p>Alkemy - Programa: POO en Python</p>
        <br>
    </footer>
</body>
</html>

stock_control/compra/templates/productos/producto_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Control</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-success border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          <span class="navbar-brand">Stock Control</span>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'compra:lista_proveedores' %}">Proveedores</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="http://127.0.0.1:8000/admin/">Admin</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    <main class="container mt-5"> 
       <h2>Crear producto</h2>
       <br>
       <form action="" method="post" class="mb-3 ">
        <div class="mb-3 ">
        {% for field in form %}
       <div class="row align-items ms-auto">
        {{field.errors}}
        {{field.label_tag}}
        {{field}}
       </div>
        <br>
        {% endfor %}
         {% csrf_token %}
        <input type="submit" value="Guardar" class="form-control btn btn-outline-success mb-4">
        </div>
       </form>
       <a class="text-muted text-decoration-none" href="{% url 'compra:lista_productos' %}">Volver a la lista de Productos</a>
    </main>
    <footer class="mt-5 p-4 bg-success bg-gradient text-white text-center">
        <br>
        <p>Alkemy - Programa: POO en Python</p>
        <br>
    </footer>
</body>
</html>

stock_control/compra/templates/proveedores/detalle_proveedor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Control</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-success border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          <span class="navbar-brand">Stock Control</span>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'compra:lista_productos' %}">Productos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="http://127.0.0.1:8000/admin/">Admin</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    <main class="container mt-5"> 
      <div class="container mb-3">
        <h1>Detalle del Producto</h1>
        <br>
        <p><strong>Nombre: </strong> {{proveedor_detalle.nombre}}</p>
        <p><strong>Apellido: </strong> {{proveedor_detalle.apellido}}</p>
        <p><strong>DNI: </strong> {{proveedor_detalle.dni}}</p>
        <hr>
        <a class="text-muted text-decoration-none" href="{% url 'compra:modificar_proveedor' proveedor_detalle.id %}">Modificar</a> 
        <a class="text-muted text-decoration-none" href="{% url 'compra:eliminar_proveedor' proveedor_detalle.id %}">Eliminar</a> 
        <a class="text-muted text-decoration-none" href="{% url 'compra:lista_proveedores' %}">Volver a la lista de Proveedores</a>
        <br>
      </div>  
    </main>
    <footer class="mt-5 p-4 bg-success bg-gradient text-white text-center">
        <br>
        <p>Alkemy - Programa: POO en Python</p>
        <br>
    </footer>
</body>
</html>

stock_control/compra/templates/proveedores/lista_proveedores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Control</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-success border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          <span class="navbar-brand">Stock Control</span>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'compra:lista_productos' %}">Productos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="http://127.0.0.1:8000/admin/">Admin</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    <main class="container mt-5"> 
        <h2>Lista de Proveedores</h2>
      <div class="mb-3 ">
        <ol class="list-group">
            {% for proveedor in proveedores %}
                <li class="list-group-item">
                  <a class="list-group-item list-group-item-action" href="{% url 'compra:detalle_proveedor' proveedor.id %}">
                    {{proveedor.nombre}} {{proveedor.apellido}}  -  {{proveedor.dni}} 
                  </a>
                </li>
            {% empty %}
                <li class="list-group-item">No existen proveedores</li>
            {% endfor %}
        </ol>
        <hr>
        <br>
        <a class="text-muted text-decoration-none" href="{% url 'compra:crear_proveedor' %}">Crear Proveedor</a>

    </main>
    <footer class="mt-5 p-4 bg-success bg-gradient text-white text-center">
        <br>
        <p>Alkemy - Programa: POO en Python</p>
        <br>
    </footer>
</body>
</html>